const articles = [
  {
    name: "The Evolution of Rock and Roll",
    genre: "Rock",
    author: "John Doe",
    place: "London",
  },
  {
    name: "The Rise of Indie Music in the Streaming Era",
    genre: "Indie",
    author: "Jane Smith",
    place: "Berlin",
  },
  {
    name: "How Jazz Revolutionized Modern Music",
    genre: "Jazz",
    author: "Alan Brown",
    place: "New Orleans",
  },
  {
    name: "Pop Music Trends to Watch in 2024",
    genre: "Pop",
    author: "Emily Davis",
    place: "Los Angeles",
  },
  {
    name: "The Role of Hip-Hop in Social Change",
    genre: "Hip-Hop",
    author: "Chris Johnson",
    place: "New York City",
  },
  {
    name: "EDM Festivals: The Heartbeat of Electronic Music",
    genre: "EDM",
    author: "Sarah Lee",
    place: "Amsterdam",
  },
  {
    name: "Exploring the Roots of Classical Music",
    genre: "Classical",
    author: "Michael Green",
    place: "Vienna",
  },
  {
    name: "The Influence of Reggae on Global Music Culture",
    genre: "Reggae",
    author: "Lisa White",
    place: "Kingston",
  },
  {
    name: "Folk Music Revival in Modern Times",
    genre: "Folk",
    author: "Tom Moore",
    place: "Dublin",
  },
  {
    name: "K-Pop's Global Domination",
    genre: "K-Pop",
    author: "Sophie Kim",
    place: "Seoul",
  },
  {
    name: "The Art of Songwriting: Insights from Top Artists",
    genre: "Various",
    author: "David Black",
    place: "Nashville",
  },
  {
    name: "Country Music: Bridging Tradition and Innovation",
    genre: "Country",
    author: "Emma Wilson",
    place: "Austin",
  },
  {
    name: "How Blues Shaped the Sound of Rock",
    genre: "Blues",
    author: "Henry Taylor",
    place: "Memphis",
  },
  {
    name: "Top 10 Albums That Changed Music History",
    genre: "Various",
    author: "James Carter",
    place: "San Francisco",
  },
  {
    name: "Understanding the Growth of Afrobeat",
    genre: "Afrobeat",
    author: "Nina Brown",
    place: "Lagos",
  },
  {
    name: "Music and Mental Health: The Healing Power of Sound",
    genre: "Wellness",
    author: "Laura Thomas",
    place: "Boulder",
  },
  {
    name: "The Impact of Streaming on the Music Industry",
    genre: "Industry",
    author: "Brian Scott",
    place: "Silicon Valley",
  },
  {
    name: "The Golden Age of Punk Music",
    genre: "Punk",
    author: "Ashley Morgan",
    place: "London",
  },
  {
    name: "R&B Icons: Artists Who Defined the Genre",
    genre: "R&B",
    author: "Steve Harris",
    place: "Atlanta",
  },
  {
    name: "Latin Music's Role in the Global Market",
    genre: "Latin",
    author: "Maria Perez",
    place: "Miami",
  },
  {
    name: "The Underground World of Experimental Music",
    genre: "Experimental",
    author: "Liam Adams",
    place: "Tokyo",
  },
  {
    name: "Film Scores: Composers Who Made History",
    genre: "Soundtrack",
    author: "Oliver Brooks",
    place: "Hollywood",
  },
  {
    name: "How Technology is Transforming Live Performances",
    genre: "Tech",
    author: "Hannah Reed",
    place: "Las Vegas",
  },
  {
    name: "The Role of Women in Music: Breaking Barriers",
    genre: "Various",
    author: "Isabella Collins",
    place: "Sydney",
  },
  {
    name: "Rap Battles and Their Cultural Significance",
    genre: "Rap",
    author: "Elijah James",
    place: "Detroit",
  },
  {
    name: "The Connection Between Music and Fashion",
    genre: "Culture",
    author: "Sophia Martin",
    place: "Paris",
  },
  {
    name: "Jazz Fusion: Where Genres Collide",
    genre: "Jazz Fusion",
    author: "Ethan Walker",
    place: "Chicago",
  },
  {
    name: "Exploring the Phenomenon of Lo-Fi Music",
    genre: "Lo-Fi",
    author: "Ava Parker",
    place: "Portland",
  },
  {
    name: "Grunge: The Sound That Defined the '90s",
    genre: "Grunge",
    author: "Mason Robinson",
    place: "Seattle",
  },
  {
    name: "The Evolution of Sound in Video Game Music",
    genre: "Video Game",
    author: "Chloe Mitchell",
    place: "Kyoto",
  },
];
const randomArticle = articles[Math.floor(Math.random() * articles.length)];

export default randomArticle;
